name: llspydev
channels:
  - talley
#  - talley/label/dev
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - scipy >=1.0.0
  - matplotlib >=3
  - tifffile >=0.15.0
  - numba >=0.38.0
  - ipython 
  - voluptuous ==0.11.1
  - watchdog >=0.8.3
  - click >=6.7
  - pip
  - pyqt >=5.9.2
  - pyopencl
  - spimagine >=0.2.6
  - sentry-sdk
  - llspy-slm
  - llspylibs >=0.1.3
  - parse
  - pigz
  - lbzip2   # mac linux only
  - tar ==1.29  # mac/linux only
  - pytest
  - pytest-qt
