name: llspydev
channels:
  - talley
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib  # matplotlib from conda tries to install qt 5.6
  - tifffile
  - numba
  - ipython
  - voluptuous
  - watchdog
  - click
  - pip
  - pyqt
  - pyopencl
  - spimagine
  - raven
  - llspy-slm
  - parse